sagify:
    
    train:
      input_s3_dir: s3://kenza-ds-demo/iris-data/iris.data
      output_s3_dir: s3://kenza-training-models
      hyperparameters_file: hyperparameters.json
      ec2_type: ml.m5.large
      volume_size: 50
      timeout: 86400
      metrics: Accuracy
